output: "grpc"
level: "info"
server_id: "semantic-service"
client_id: "semantic-service"
grpc:
  address: "0.0.0.0"
  port: 50052
server:
  address: "0.0.0.0"
  port: 50059
endpoint_client:
  default_address: "http://0.0.0.0:50057"
log_fields:
  include_thread_id: true
  include_target: true
  include_file: true
  include_line: true
  include_timestamp: true
client_retry:
  max_retries: 5000
  base_delay_secs: 1
  reconnect_delay_secs: 5
log_all_messages: false

# Model configurations
models:
  sentence_to_json:
    cohere: "command-r7b-12-2024"
    claude: "claude-3-5-sonnet-20241022"
    deepseek: "deepseek-chat"
    temperature: 0.1
    max_tokens: 1000
  find_endpoint:
    cohere: "command-r7b-12-2024"
    claude: "claude-3-5-sonnet-20241022"
    deepseek: "deepseek-chat"
    temperature: 0.1
    max_tokens: 500
  semantic_match:
    cohere: "command-r7b-12-2024"
    claude: "claude-3-5-sonnet-20241022"
    deepseek: "deepseek-chat"
    temperature: 0.1
    max_tokens: 500
  intent_classification:
    cohere: "command-r7b-12-2024"
    claude: "claude-3-5-sonnet-20241022"
    deepseek: "deepseek-chat"
    temperature: 0.1
    max_tokens: 50

# Provider configurations
providers:
  cohere:
    enabled: true
    api_key: "" # Will be loaded from .env
  claude:
    enabled: true
    api_key: "" # Will be loaded from .env
  deepseek:
    enabled: true
    api_key: "" # Will be loaded from .env
service:
  name: semantic
  version: 1.0.0
  provider: cohere
  api: "http://127.0.0.1:50057"

analysis:
  retry_attempts: 3
  fallback_to_general: true
