#!/bin/bash
# example.sh - Show how to use semantic with Cohere

echo "==================================================="
echo "           Semantic - Usage Examples                "
echo "              (Cohere API Only)                     "
echo "==================================================="
echo ""
echo "SERVER MODE (no email required):"
echo "-------------------"
echo "1. Start server with Cohere:"
echo "   cargo run"
echo ""
echo ""
echo "CLI MODE (email required):"
echo "-------------------"
echo "2. Analyze text with Cohere:"
echo "   cargo run -- --email user@example.com \"analyze this text\""
echo ""
echo "3. Analyze with remote endpoints:"
echo "   cargo run -- --api http://example.com:50053 --email user@example.com \"analyze this text\""
echo ""
echo "4. Show help:"
echo "   cargo run -- --help"
echo ""
echo "IMPORTANT: Email is required ONLY when analyzing a sentence!"
echo ""
echo "Remember to set up your .env file with COHERE_API_KEY."
